### ISSUE TITLE
apache_beam is installed but still refuses to be found.

### ISSUE THREAD

**Issue by RobertSvebeck** [GeorgLegato/stable-diffusion-webui-sequencor#1]
Tried to solve this myself but I get nowhere. pip list shows that apache-beam is installed with version 2.46.0

I get this error when starting auto1111

Have followed the installation instructions but I am not using vlad, so perhaps it's that?

Error loading script: sequencor.py
Traceback (most recent call last):
  File "E:\GitHub\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "E:\GitHub\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\GitHub\stable-diffusion-webui\extensions\stable-diffusion-webui-sequencor\scripts\sequencor.py", line 7, in <module>
    from scripts.processors import film_cli_adapt
  File "E:\GitHub\stable-diffusion-webui\extensions\stable-diffusion-webui-sequencor\scripts\processors\film_cli_adapt.py", line 6, in <module>
    import scripts.processors.FILM.interpolator_cli as interpolate_cli
  File "E:\GitHub\stable-diffusion-webui\extensions\stable-diffusion-webui-sequencor\scripts\processors\FILM\interpolator_cli.py", line 74, in <module>
    import apache_beam as beam
ModuleNotFoundError: No module named 'apache_beam'

**Comment by GeorgLegato** [comment]
i will try that on auto111 myself. I started yesterday this project and was only on Vlads fork

**Comment by RobertSvebeck** [comment]
Did you get it to work in auto1111?

**Comment by GeorgLegato** [comment]
I got up using vlads latest. the requirements.txt reflects a compromise between vlad and FILM.
I am afraid to avoid venv-clashing auto1111 and vlad, so  the extension shall setup its own venv internally, python is a huge disk space eating dependencie monster. problem here might be Sd-python code will call python code from other venv... cross-venv-calls possible?

**Comment by GeorgLegato** [comment]
update please; i tweaked some requirements for FILM, on my machine it works in vlad and auto1111
[5a9c1ef](https://github.com/GeorgLegato/stable-diffusion-webui-sequencor/commit/5a9c1ef49db35b250419076b6c7343ae33e2b256)

**Comment by RobertSvebeck** [comment]
I have updated but I get the same error at auto1111 launch. Same error. No module named 'apache_beam'

**Comment by GeorgLegato** [comment]
please give log file from console. sometime on loading module it is the module being loaded before, which causes error
it should be possible to fix, I got em both running for auto1111 and vlad

**Comment by RobertSvebeck** [comment]
I am guessing my issue is around something in the venv but I am not good at this so.... anyway here is the complete console: 

```
venv "E:\GitHub\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 5ab7f213bec2f816f9c5644becb32eb72c8ffb89
Installing requirements

current transparent-background 1.2.3

Installing requirements 1 for Infinite-Zoom
Installing imageio-ffmpeg requirement for depthmap script
Installing pyqt5 requirement for depthmap script
Installing sd-sequencor requirements.txt

Launching Web UI with arguments: --no-half --xformers --disable-safe-unpickle
==============================================================================
You are running torch 1.13.1+cu117.
The program is tested to work with torch 2.0.0.
To reinstall the desired version, run with commandline flag --reinstall-torch.
Beware that this will cause a lot of large files to be downloaded, as well as
there are reports of issues with training tab on the latest version.

Use --skip-version-check commandline argument to disable this check.
==============================================================================
=================================================================================
You are running xformers 0.0.16rc425.
The program is tested to work with xformers 0.0.17.
To reinstall the desired version, run with commandline flag --reinstall-xformers.

Use --skip-version-check commandline argument to disable this check.
=================================================================================
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
ControlNet v1.1.140
ControlNet v1.1.140
Error loading script: sequencor.py
Traceback (most recent call last):
  File "E:\GitHub\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "E:\GitHub\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\GitHub\stable-diffusion-webui\extensions\stable-diffusion-webui-sequencor\scripts\sequencor.py", line 7, in <module>
    from scripts.processors import film_cli_adapt,rife_cli_adapter
  File "E:\GitHub\stable-diffusion-webui\extensions\stable-diffusion-webui-sequencor\scripts\processors\film_cli_adapt.py", line 6, in <module>
    import scripts.processors.FILM.interpolator_cli as interpolate_cli
  File "E:\GitHub\stable-diffusion-webui\extensions\stable-diffusion-webui-sequencor\scripts\processors\FILM\interpolator_cli.py", line 74, in <module>
    import apache_beam as beam
ModuleNotFoundError: No module named 'apache_beam'


Loading weights [ad2a33c361] from E:\GitHub\stable-diffusion-webui\model.ckpt
Creating model from config: E:\GitHub\stable-diffusion-webui\model.yaml
LatentDiffusion: Running in v-prediction mode
DiffusionWrapper has 865.91 M params.
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(1): midjourney
Textual inversion embeddings skipped(1): svebeck-art
Model loaded in 5.3s (load weights from disk: 1.6s, create model: 0.2s, apply weights to model: 0.7s, move model to device: 1.9s, load textual inversion embeddings: 1.0s).
load Sadtalker Checkpoints from E:\GitHub\stable-diffusion-webui\extensions\SadTalker\checkpoints
*Deforum ControlNet support: enabled*
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 25.1s (import torch: 6.8s, import gradio: 1.2s, import ldm: 0.9s, other imports: 1.0s, setup codeformer: 0.1s, load scripts: 6.3s, load SD checkpoint: 5.5s, create ui: 3.0s, gradio launch: 0.3s).
```
runing pip list in the venv gives me this:

```
(venv) E:\GitHub\stable-diffusion-webui\venv\Scripts>py -m pip list
Package                       Version
----------------------------- ---------------
..
apache-beam                   2.46.0
...
```

so the way I understand things, which is very limited.... it is installed, in the virtual environment...

**Comment by GeorgLegato** [comment]
i cant see what could be wrong.

so, lets dig around. here my complete list of a somehow working setup..
btw, the FILM stuff is actually very lame. slow and the results are not that better to invest that time.
Best would be, I kick FILM completely and you concentrate on RIFE


(venv) S:\KI\stable-diffusion-webui1111>python -m pip list
Package                       Version
----------------------------- ------------------
absl-py                       1.4.0
accelerate                    0.18.0
addict                        2.4.0
aenum                         3.1.11
aiofiles                      23.1.0
aiohttp                       3.8.4
aiosignal                     1.3.1
altair                        4.2.2
antlr4-python3-runtime        4.9.3
anyio                         3.6.2
apache-beam                   2.46.0
appdirs                       1.4.4
asttokens                     2.2.1
astunparse                    1.6.3
async-timeout                 4.0.2
asyncer                       0.0.2
attrs                         22.2.0
audioread                     3.0.0
av                            10.0.0
backcall                      0.2.0
basicsr                       1.4.2
beautifulsoup4                4.12.0
blendmodes                    2022
boltons                       23.0.0
cachetools                    5.3.0
certifi                       2022.12.7
cffi                          1.15.1
chardet                       4.0.0
charset-normalizer            2.1.1
clean-fid                     0.1.29
click                         8.1.3
clip                          1.0
cloudpickle                   2.2.1
color-matcher                 0.5.0
colorama                      0.4.6
coloredlogs                   15.0.1
contourpy                     1.0.7
crcmod                        1.7
cssselect2                    0.7.0
cssutils                      2.6.0
cycler                        0.11.0
ddt                           1.6.0
decorator                     4.4.2
deprecation                   2.1.0
dill                          0.3.1.1
dlib-bin                      19.24.1
docopt                        0.6.2
docutils                      0.19
easydict                      1.10
einops                        0.4.1
entrypoints                   0.4
executing                     1.2.0
face-alignment                1.3.5
facexlib                      0.2.5
fastapi                       0.94.0
fastavro                      1.7.3
fasteners                     0.18
ffmpy                         0.3.0
ffprobe                       0.5
filelock                      3.9.0
filetype                      1.2.0
filterpy                      1.4.5
flatbuffers                   23.3.3
font-roboto                   0.0.1
fonts                         0.0.3
fonttools                     4.39.2
freetype-py                   2.3.0
frozenlist                    1.3.3
fsspec                        2023.3.0
ftfy                          6.1.1
future                        0.18.3
fvcore                        0.1.5.post20221221
gast                          0.4.0
gdown                         4.5.4
gfpgan                        1.3.8
gin-config                    0.5.0
gitdb                         4.0.10
GitPython                     3.1.30
google-api-core               1.34.0
google-auth                   2.16.3
google-auth-oauthlib          0.4.6
google-cloud-bigquery-storage 1.1.0
google-pasta                  0.2.0
googleapis-common-protos      1.59.0
gradio                        3.28.1
gradio_client                 0.1.4
greenlet                      2.0.2
grpcio                        1.51.3
grpcio-status                 1.48.2
h11                           0.12.0
h5py                          3.8.0
hdfs                          2.7.0
hsluv                         5.0.3
httpcore                      0.15.0
httplib2                      0.21.0
httpx                         0.23.3
huggingface-hub               0.13.3
humanfriendly                 10.0
idna                          2.10
ImageHash                     4.3.1
imageio                       2.26.1
imageio-ffmpeg                0.4.7
inflection                    0.5.1
invisible-watermark           0.1.5
iopath                        0.1.9
ipython                       8.11.0
jax                           0.4.8
jedi                          0.18.2
Jinja2                        3.1.2
joblib                        1.2.0
jsonmerge                     1.8.0
jsonpatch                     1.32
jsonpointer                   2.3
jsonschema                    4.17.3
keras                         2.12.0
kiwisolver                    1.4.4
kornia                        0.6.7
lark                          1.1.2
lazy_loader                   0.2
libclang                      16.0.0
librosa                       0.8.0
lightning-utilities           0.8.0
linkify-it-py                 2.0.0
llvmlite                      0.39.1
lmdb                          1.4.0
lpips                         0.1.4
lxml                          4.9.2
Markdown                      3.4.3
markdown-it-py                2.2.0
MarkupSafe                    2.1.2
matplotlib                    3.7.1
matplotlib-inline             0.1.6
mdit-py-plugins               0.3.3
mdurl                         0.1.2
mediapipe                     0.9.3.0
mediapy                       1.1.6
ml-dtypes                     0.1.0
moviepy                       1.0.2
mpmath                        1.2.1
multidict                     6.0.4
mypy-extensions               1.0.0
natsort                       8.1.0
networkx                      3.0
numba                         0.56.4
numexpr                       2.8.4
numpy                         1.23.5
oauthlib                      3.2.2
objsize                       0.6.1
omegaconf                     2.2.3
onnx                          1.13.1
onnxruntime                   1.13.1
onnxruntime-gpu               1.14.1
open-clip-torch               2.7.0
opencv-contrib-python         4.7.0.72
opencv-python                 4.7.0.72
opencv-python-headless        4.6.0.66
opt-einsum                    3.3.0
orjson                        3.8.8
packaging                     23.0
pandas                        1.5.3
parameterized                 0.8.1
parso                         0.8.3
pickleshare                   0.7.5
piexif                        1.1.3
Pillow                        9.4.0
PIMS                          0.6.0
pip                           23.0.1
pooch                         1.6.0
portalocker                   2.7.0
proglog                       0.1.10
promise                       2.3
prompt-toolkit                3.0.38
proto-plus                    1.22.2
protobuf                      3.20.3
psutil                        5.9.4
pure-eval                     0.2.2
pyaml                         21.10.1
pyarrow                       9.0.0
pyasn1                        0.4.8
pyasn1-modules                0.2.8
pycocotools                   2.0.6
pycparser                     2.21
pycryptodome                  3.17
pydantic                      1.10.7
pyDeprecate                   0.3.2
pydot                         1.4.2
pydub                         0.25.1
Pygments                      2.14.0
PyMatting                     1.1.8
pymongo                       3.13.0
pyparsing                     3.0.9
PyQt5                         5.15.9
PyQt5-Qt5                     5.15.2
PyQt5-sip                     12.11.1
pyre-extensions               0.0.23
pyreadline3                   3.4.1
pyrsistent                    0.19.3
PySocks                       1.7.1
python-dateutil               2.8.2
python-multipart              0.0.6
pytorch-lightning             1.9.4
pytz                          2023.2
pyvirtualcam                  0.10.2
PyWavelets                    1.4.1
pywin32                       306
PyYAML                        6.0
realesrgan                    0.3.0
regex                         2023.3.23
rembg                         2.0.30
reportlab                     3.6.12
requests                      2.25.1
requests-oauthlib             1.3.1
resampy                       0.4.2
resize-right                  0.0.2
rfc3986                       1.5.0
rich                          13.3.2
rsa                           4.9
safetensors                   0.3.1
scikit-fmm                    2023.4.2
scikit-image                  0.19.2
scikit-learn                  1.2.2
scipy                         1.9.3
seaborn                       0.12.2
segment-anything              1.0
segmentation-refinement       0.6
semantic-version              2.10.0
Send2Trash                    1.8.0
sentencepiece                 0.1.97
setuptools                    63.2.0
six                           1.16.0
slicerator                    1.1.0
smmap                         5.0.0
sniffio                       1.3.0
sounddevice                   0.4.6
soundfile                     0.12.1
soupsieve                     2.4
SQLAlchemy                    2.0.9
stack-data                    0.6.2
starlette                     0.26.1
svglib                        1.5.1
svgpathtools                  1.6.0
svgwrite                      1.4.3
sympy                         1.11.1
tabulate                      0.9.0
tb-nightly                    2.13.0a20230317
tensorboard                   2.12.0
tensorboard-data-server       0.7.0
tensorboard-plugin-wit        1.8.1
tensorflow                    2.12.0
tensorflow-addons             0.16.1
tensorflow-datasets           4.4.0
tensorflow-estimator          2.12.0
tensorflow-intel              2.12.0
tensorflow-io-gcs-filesystem  0.31.0
tensorflow-metadata           1.13.1
termcolor                     2.2.0
threadpoolctl                 3.1.0
tifffile                      2023.3.21
timm                          0.6.7
tinycss2                      1.2.1
tokenizers                    0.13.2
toolz                         0.12.0
torch                         2.0.0+cu118
torch-tools                   0.1.5
torchdiffeq                   0.2.3
torchmetrics                  0.11.4
torchsde                      0.2.5
torchvision                   0.15.1+cu118
tornado                       6.2
tqdm                          4.65.0
traitlets                     5.9.0
trampoline                    0.1.2
transformers                  4.25.1
transforms3d                  0.2.1
transparent-background        1.2.3
trimesh                       3.21.5
typeguard                     3.0.2
typing_extensions             4.4.0
typing-inspect                0.8.0
uc-micro-py                   1.0.1
urllib3                       1.26.13
uvicorn                       0.20.0
visdom                        0.2.4
vispy                         0.12.2
watchdog                      2.1.9
wcwidth                       0.2.6
webencodings                  0.5.1
websocket-client              1.5.1
websockets                    10.4
Werkzeug                      2.2.3
wheel                         0.40.0
wrapt                         1.14.1
xformers                      0.0.18
yacs                          0.1.8
yapf                          0.32.0
yarl                          1.8.2
zstandard                     0.21.0

**Comment by RobertSvebeck** [comment]
Based on your list, I am missing theese. Can you see directly if anything is important for Sequencor? There are also differences in versions on some other packages, and I have a bunch that you do not have, but perhaps easiest to start with those completely missing.

appdirs 1.4.4
asyncer 0.0.2
audioread 3.0.0
av 10.0.0
color-matcher 0.5.0
cssselect2 0.7.0
cssutils 2.6.0
ddt 1.6.0
dlib-bin 19.24.1
docutils 0.19
easydict 1.10
face-alignment 1.3.5
ffprobe 0.5
filetype 1.2.0
freetype-py 2.3.0
fvcore 0.1.5.post20221221
greenlet 2.0.2
hsluv 5.0.3
ImageHash 4.3.1
imageio-ffmpeg 0.4.7
iopath 0.1.9
joblib 1.2.0
jsonpatch 1.32
jsonpointer 2.3
lazy_loader 0.2
librosa 0.8.0
lightning-utilities 0.8.0
lpips 0.1.4
lxml 4.9.2
mediapipe 0.9.3.0
moviepy 1.0.2
numexpr 2.8.4
onnxruntime-gpu 1.14.1
open-clip-torch 2.7.0
opencv-python-headless 4.6.0.66
PIMS 0.6.0
pooch 1.6.0
portalocker 2.7.0
proglog 0.1.10
pyaml 21.10.1
pycocotools 2.0.6
pycryptodome 3.17
pydantic 1.10.7
PyMatting 1.1.8
PyQt5 5.15.9
PyQt5-Qt5 5.15.2
PyQt5-sip 12.11.1
pyvirtualcam 0.10.2
pywin32 306
rembg 2.0.30
reportlab 3.6.12
resampy 0.4.2
scikit-fmm 2023.4.2
scikit-learn 1.2.2
seaborn 0.12.2
segment-anything 1.0
segmentation-refinement 0.6
Send2Trash 1.8.0
sentencepiece 0.1.97
slicerator 1.1.0
sounddevice 0.4.6
soundfile 0.12.1
SQLAlchemy 2.0.9
svglib 1.5.1
svgpathtools 1.6.0
svgwrite 1.4.3
tabulate 0.9.0
threadpoolctl 3.1.0
tinycss2 1.2.1
torch-tools 0.1.5
tornado 6.2
transforms3d 0.2.1
transparent-background 1.2.3
trimesh 3.21.5
visdom 0.2.4
vispy 0.12.2
watchdog 2.1.9
webencodings 0.5.1
websocket-client 1.5.1
yacs 0.1.8

**Comment by GeorgLegato** [comment]
what is important for FILM as part of sequencor goto its requirements.txt
when you did the pip -install onthat requirements.txt(which changed two days ago) you should have all needed packages.
Now, they could clash with packages from other extensions you have installed.
it is a mess, when plugins are touching the host venv, actually.
RIFE is so easy by providing an simple exe file....
